name: build-windows

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PySide6

      - name: Build (onedir)
        shell: pwsh
        run: |
          pyinstaller types_generator_onedir.spec --clean

      - name: Compute checksums
        shell: pwsh
        run: |
          $folder = "dist/Dayz Types Generator"
          Get-ChildItem -Recurse $folder | ForEach-Object {
            if (-not $_.PSIsContainer) {
              $hash = Get-FileHash -Algorithm SHA256 $_.FullName
              "$($hash.Hash)  $($_.FullName)" | Out-File -Append -Encoding utf8 checksums.txt
            }
          }
          Get-Content checksums.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Dayz-Types-Generator-windows-onedir
          path: |
            dist/Dayz Types Generator/**
            checksums.txt

      # Optional: Create GitHub Release when tagging vX.Y.Z
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/Dayz Types Generator/**/*
            checksums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
